import gl
gl.resetdefaults()
#opacity adjusts whether overlays are translucent (0)
opacity = 50
pth = '/Users/chris/Downloads/sf/'
gl.azimuthelevation(70, 15)
gl.meshload('BrainMesh_ICBM152_smoothed.mz3')
gl.overlayload(pth+'bin.thr.ACC_LR.nii.gz')
gl.overlaycolorname(1, 'Violet [r+b]')
gl.overlayminmax(1,0.5,0.5)
gl.overlayopacity(1, opacity)
gl.overlayload(pth+'bin.thr.S2_OP1_LR.nii.gz')
gl.overlaycolorname(2, 'Violet [r+b]')
gl.overlayminmax(2,0.5,0.5)
gl.overlayopacity(2, opacity)
gl.overlayload(pth+'bin.thr.INS_LR.nii.gz')
gl.overlaycolorname(3, 'Bronze-Gold')
gl.overlayminmax(3,0.5,0.5)
gl.overlayopacity(3, opacity)
gl.overlayload(pth+'bin.thr.Tha_LR.nii.gz')
gl.overlaycolorname(4, 'Blue')
gl.overlayminmax(4,0.5,0.5)
gl.overlayopacity(4, opacity)
gl.overlayload(pth+'bin.thr.S1_BA2_LR.nii.gz')
gl.overlaycolorname(5, 'Cyan [g+b]')
gl.overlayminmax(5,0.5,0.5)
gl.overlayopacity(5, opacity)
gl.overlayload(pth+'thresh_zstat1.nii.gz')
gl.overlaycolorname(6, 'Red')
gl.overlayminmax(6,0.5,0.5)
gl.overlayopacity(6, 100)
gl.meshcurv()