.TH "SURFICE" "1" "September 2021" "Chris Rorden" "User Commands"
.SH NAME
surfice \- neuroimaging mesh viewing tool
.SH "DESCRIPTION"
Surfice is a GUI-based visualization and analysis tool for neuroimaging 
data. It can display triangulated meshes in many formats, including 
PLY, GIfTI, FreeSurfer, and OBJ. Surfice can also display diffusion tensor
tractography maps from various formats including TRK and TCK. In addition, 
it is able to show connectome maps.
.SH "AUTHOR"
\fBsurfice\fR was written by Chris Rorden.
.PP
This manual page was written by Chris Rorden,
for the Debian project (but may be used by others).
.SH "SEE ALSO"
.BR dcm2niix "(1)"
.TP
\fBSurfice Homepage and Wiki:\fR https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage
