.TH "SURFICE" "1" "December 2021" "Yaroslav Halchenko" "User Commands"
.SH NAME
surfice \- neuroimaging mesh, tractography, connectome viewing
.SH "DESCRIPTION"
Surfice is a GUI-based visualization tool for neuroimaging mesh, tractography and connectome formats.
.SH "AUTHOR"
\fBsurfice\fR was written by Chris Rorden.
.PP
This manual page was written by Yaroslav Halchenko <debian@onerussian.com>,
for the Debian project (but may be used by others).
.SH "SEE ALSO"
.BR dcm2niix "(1)"
.TP
\fBSurfice Homepage:\fR https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage
